org: saatwik
app: serverless-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: deploy-project

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: ap-south-1

layers: ${file(./layers.yml)}

functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: UtilsLambdaLayer }

plugins:
  - serverless-python-requirements
