name: Deploy Serverless V4 project

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master 

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev

    strategy:
      matrix:
        node-version: [20.x]
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Execute Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Create layers
      run: |
          mkdir -p layer/python/Utils # creating new directory for layers.
          cp -R ./Utils/ layer/python/ # copying Utils folder into layers/python/ folder
          pip install -r ./Utils/requirements.txt --target .layer/python/
    - run: npm install
    - name: serverless deploy
      uses: serverless/github-action@v4
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
